bracketSameLine: false
bracketSpacing: true
printWidth: 120
singleQuote: true
semi: true
tabWidth: 2
trailingComma: 'all'
useTabs: false

plugins:
  - 'prettier-plugin-astro'

overrides:
  - files: '*.astro'
    options:
      parser: 'astro'
